# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Label issues
on:
  issues:
    types:
      - reopened
      - opened
jobs:
  label_issues:
    if: github.repository == 'surfstudio/surf-flutter-app-template'
    uses: surfstudio/flutter-ci-workflows/.github/workflows/new_issues_label.yml@main
    secrets:
      SECRET_ISSUES: ${{ secrets.ACCESS_TOKEN_FOR_SURFGEAR }}
