name: "Testing"

on:
  workflow_call:
    secrets:
      CODECOV_TOKEN:
        required: true
    inputs:
      flutter-version:
        required: false
        type: string

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Flutter with exact version
        if: ${{ inputs.flutter-version != ''}}
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ inputs.flutter-version }}

      - name: Install Flutter from Stable branch
        if: ${{ inputs.flutter-version == ''}}
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Install dependencies
        run: flutter pub get

      - name: Generate files
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Run tests
        env:
          CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
        if: success()
        run: |
          flutter test --coverage
          bash <(curl -s https://codecov.io/bash) -f coverage/lcov.info